name: "Action Error Report / CI 에러 보고"
description: Report GitHub Actions failures (unitTest → RobolectricTest → build → Release). / GitHub Actions 단계 에러를 공유해주세요.
#labels: ["ci", "needs-triage"]
body:
  - type: dropdown
    id: failed_stage
    attributes:
      label: Failed stage / 실패한 단계
      description: Select the step that failed. / 실패한 단계를 선택하세요.
      options:
        - Unit Tests
        - Robolectric Tests
        - Build and Lint Check
        - Release from Commit Message
    validations:
      required: true

  - type: input
    id: workflow_url
    attributes:
      label: Workflow run URL
      placeholder: https://github.com/owner/repo/actions/runs/1234567890
    validations:
      required: true

  - type: input
    id: commit_sha
    attributes:
      label: Commit SHA (optional) / 커밋 SHA(선택)
      placeholder: e.g., 1a2b3c4d

  - type: textarea
    id: summary
    attributes:
      label: Failure summary / 실패 요약
      description: What broke? Include observable symptoms. / 어떤 현상이 발생했나요?
      placeholder: e.g., build task :simple_ui:testDebugUnitTest failed with exit code 1...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log excerpt / 관련 로그
      description: Paste the relevant portion of the Actions log. / 필요한 로그 일부를 붙여주세요.
      render: shell
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Extra context (optional) / 추가 정보(선택)
      placeholder: Custom secrets, matrix values, feature flags, etc.
