name: "First-Run Feedback / 첫 실행 피드백"
description: Tell us where you got stuck. / 어디서 막혔는지 알려주세요.
labels: [ "first-run", "needs-triage" ]
body:
  - type: input
    id: version
    attributes:
      label: Library Release version
      placeholder: 0.2.1

  - type: textarea
    id: yourAppVersion
    attributes:
      label: Application build version
      placeholder: kotlin version, min sdk, target sdk, compile sdk, AGP version.. etc version

  - type: textarea
    id: deviceInfo
    attributes:
      label: Testing device info
      placeholder: device model name, OS version, device state,(wifi on/off, network connect/disconnect..etc)

  - type: textarea
    id: steps
    attributes:
      label: Steps & Timestamp / 재현 단계와 시각
      placeholder: 1) ... 2) ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual / 기대 vs 실제
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots (optional) / 로그·스크린샷(선택)

  - type: input
    id: ttfh
    attributes:
      label: Time To First Hello (mins, optional) / 첫 성공까지 분(선택)

  - type: textarea
    id: ideas
    attributes:
      label: Quick win you wish existed (optional) / 바로 있었으면 하는 개선(선택)
